export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";




export const CLEAR_STATE="CLEAR_STATE"
export const ORDER_NAME = "ORDER_NAME"
export const ORDER_RATING ="ORDER_RATING"
export const ORDER_PRICE ="ORDER_PRICE"
export const ORDER_COUNTINSTOCK ="ORDER_COUNTINSTOCK"



 
//* Categories

export const GET_ALL_CATEGORY ="GET_ALL_CATEGORY"
export const FILTER_BY_TYPES_CATEGORY ="FILTER_BY_TYPES_CATEGORY"