export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const POST_CATEGORIES = "POST_CATEGORIES";
export const CATEGORIES_DELETE_REQUEST ="CATEGORIES_DELETE_REQUEST"
export const CATEGORIES_DELETE_SUCCESS ="CATEGORIES_DELETE_SUCCESS"
export const CATEGORIES_DELETE_FAIL ="CATEGORIES_DELETE_FAIL"